# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Asunto', models.CharField(default='Asunto', max_length=256)),
                ('Mensaje', models.CharField(default='Mensaje', max_length=256)),
                ('FechaDeCreacion', models.DateTimeField(auto_now_add=True)),
                ('CuentaDelUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
