# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20180414_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_usuario_contacto', models.CharField(max_length=256)),
                ('text_email_contacto', models.EmailField(max_length=254)),
                ('text_asunto_contacto', models.CharField(max_length=256)),
                ('text_texo_del_contacto', models.CharField(max_length=256)),
                ('fecha_de_comentario', models.DateTimeField(auto_now_add=True)),
                ('link_imagen', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
