# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Remitente',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
