# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20180416_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='CuentaDelUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
