# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='Mi nombre...', max_length=256)),
                ('Direccion', models.CharField(default='Mi dirección...', max_length=256)),
                ('Pais', models.CharField(default='Mi país...', max_length=256)),
                ('Nacimiento', models.CharField(default='Mi fecha de nacimiento...', max_length=256)),
                ('Edad', models.CharField(default='Mi edad...', max_length=256)),
                ('Dni', models.CharField(default='Mi D.N.I...', max_length=256)),
                ('Email', models.CharField(default='Mi correo electrónico...', max_length=256)),
                ('Telefono', models.CharField(default='Mi número...', max_length=256)),
                ('EducacionPrimaria', models.CharField(default='Mi Educacíon primaria...', max_length=256)),
                ('EducacionSecundaria', models.CharField(default='Mi Educacíon secundaria...', max_length=256)),
                ('EducacionOtro', models.CharField(default='Mi Educacíon orientada...', max_length=256)),
                ('EducacionDeImportancia', models.CharField(default='Otros estudios...', max_length=256)),
                ('OtrosConocimientos', models.CharField(default='Otros conocimentos...', max_length=256)),
                ('IdiomaNativo', models.CharField(default='mi idioma...', max_length=256)),
                ('IdiomaSecundario', models.CharField(default='Idioma...', max_length=256)),
                ('IdiomaTerciario', models.CharField(default='Idioma...', max_length=256)),
                ('Informatica', models.CharField(default='Conocimientos de Informática...', max_length=256)),
                ('EspectativaDePuesto', models.CharField(default='Espectativa de puesto...', max_length=256)),
                ('ExperienciaLaboral', models.CharField(default='Mis experiencias laborales...', max_length=256)),
                ('DiasInscripto', models.DateTimeField(auto_now_add=True)),
                ('FechaDeLaUltimaEdicion', models.DateTimeField(auto_now_add=True)),
                ('MostrarCV', models.BooleanField(default=True)),
                ('CuentaPaga', models.BooleanField(default=False)),
                ('CuentaDelUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
