# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Curriculums', '0003_diplomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginasWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(default='Agregar una Web', max_length=256)),
                ('CuentaDelUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='diplomas',
            name='link',
            field=models.CharField(default='Agregar un Diploma', max_length=256),
        ),
    ]
