# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Curriculums', '0004_auto_20180407_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FotoDePerfil', models.CharField(default='Agregar una foto de perfil', max_length=256)),
                ('FotoDePortada', models.CharField(default='Agregar una foto de portada', max_length=256)),
                ('NumeroDeTelefono', models.CharField(default='Mi número...', max_length=256)),
                ('DeQueTrabajo', models.CharField(default='Mi E-mail', max_length=256)),
                ('SegundoFactorDeAutentificacion', models.BooleanField(default=True)),
                ('CuentaDelUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
