# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculums', '0008_auto_20180412_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='FotoDePerfil',
            field=models.CharField(default='Agregar un Link', max_length=256),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='FotoDePortada',
            field=models.CharField(default='Agregar un Link', max_length=256),
        ),
    ]
