# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculums', '0012_auto_20180509_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyers',
            name='flyers',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
