# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 17:24
from __future__ import unicode_literals

import Curriculums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculums', '0015_remove_flyers_nombrearchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomas',
            name='diploma',
            field=models.ImageField(blank=True, null=True, upload_to=Curriculums.models.generate_path_flyer),
        ),
        migrations.AlterField(
            model_name='diplomas',
            name='link',
            field=models.CharField(default='www.tecnologiasdedicadas.com/Curriculum/{{ user.pk }}', max_length=256),
        ),
        migrations.AlterField(
            model_name='flyers',
            name='link',
            field=models.CharField(default='www.tecnologiasdedicadas.com/Curriculum/{{ user.pk }}', max_length=256),
        ),
    ]
