# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 07:54
from __future__ import unicode_literals

import Curriculums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Curriculums', '0017_auto_20180509_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoDelPortada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FotoDePortada', models.ImageField(blank=True, null=True, upload_to=Curriculums.models.generate_path)),
                ('CuentaDelUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoDePerfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FotoDePerfil', models.ImageField(blank=True, null=True, upload_to=Curriculums.models.generate_path_avatar)),
                ('CuentaDelUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='FotoDePerfil',
        ),
        migrations.RemoveField(
            model_name='datosusuario',
            name='FotoDePortada',
        ),
    ]
