# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculums', '0018_auto_20180510_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='UsuarioDestacado',
            field=models.BooleanField(default=False),
        ),
    ]
