# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculums', '0019_datosusuario_usuariodestacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='UsuarioDestacados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='pkUsuario',
            field=models.IntegerField(default=0),
        ),
    ]
